---
title: " "
---

```{css, echo=FALSE}

h3:before { <br> }
```

## 2024

### 2024-08-12

回普陀，小区本来是沿着苏州河的，梦里却变成了大海。海水清蓝，浪花奶白，拍打在沙滩上甚是好看。mentor叫我一起下水游泳，他走得快已经下海了，而我还磨磨蹭蹭在岸边，眼看着浪突然大了起来，想想我的垃圾游泳水平，还是不下水了。此时突然巨浪滔天，很多游泳的人被一个浪盖头就再也找不见踪影。小区的救生皮阀下水了，却也无能为力。仔细找寻mentor半天，发现他水性极佳，竟然自己游上岸了，上岸后还怪我怎么不一起去游。我os：幸亏没下去好吧。

收拾东西正准备回家时，伴着巨浪天色突变，刹那间电闪雷鸣。一个闪电劈中了路边行道树，树干焦黑砸了下来，人群纷纷躲避。没想到闪电接着一个又一个地劈向路边的树。我害怕走到树下也被劈，也不知应该往何处躲避，只好站在空地处。此时闪电又开始击中一个个小区高楼，电机烧毁爆炸，大楼立马停电。一下子天也黑了，小区里也没太多照明。我拿出手机想要拍下这惊骇之幕，刚举起手机打开摄像模式，却发现我正对着的楼高处有人跳楼，看着他在手机镜头里越来越近，反应过来的时候已经砸到脚边变成一滩肉泥。

我惊叫一声，想要往回走。很多居民因为停电也来到楼下避险，还不知道发生了什么。在人群中挤出一条路，想从小桥绕道回家，却又被前方一群人拦住。此时小区广播响起“亲爱的居民朋友，如遇到可疑人等在夜间跳类似广播体操，请立即逃离，因为他们在招邪”。我定睛一看，桥上拦路人正是一群穿着相似的人都高举双臂成一个诡异姿态，脸上表情木讷。一串人从不知何时干涸的河道里一个个蹦上岸，排着队不知去向何方。

我登时头皮发麻，吓醒了。

</br>

## 2020

### 2020-10-13

放假最后一天，和一帮同学在海滩旁边玩，一派骄奢淫逸的场景，甚至有人在海里吃起了火锅。我在飙水上摩托车，路遇恶霸调戏美女，开过去就是一jio。反正玩到晚上天黑，海滩开始清场，大家就熙熙攘攘抱着家当各回各家。某路人忽然抬头说了一句，今天夜相很奇怪啊。我也抬头一看，发现乌云密布遮了一轮的月亮旁边，突然又多出了一轮小月牙。乌云褶了又散，另一边也多了一个小月亮，一时间天上竟同时出现了三个月亮。路人喝高了，还挺高兴，说这就是3d大月亮吗。再一晃神天上的景象让他彻底酒醒了，竟出现了一连串的小“月亮”，所有人都知道那不再是月亮了。我喃喃道“七星连珠么....”。路人问我什么是七星连珠，我说就是太阳系几大行星连成一线的情况发生，星体之间的相互引力会指数级上升，之后会发生什么没有人知道。路人吓坏了，问是不是该准备跑路，人群也都很焦虑不安，很多人已经撒丫子狂奔起来。我说，最有可能的事情就是地球毁灭，那不如想想怎么自杀最舒服（。

在回家的路上，情况已经不对劲了，大家跑的跑散的散。而我还没有回到家，就碰上了熟人，越聚越多，形成了一批人准备避灾。这群人中的A将我们引导到了一处封闭下沉石塔，让我们穿过去就可以安全。这石塔内部只有旋转石梯，时上时下，方向莫辨，走得昏天黑地都还没能走完，人群在这一过程中逐渐前后分散了。我一开始走在前面还试图让大家保持统一，后来实在是首尾不相接，等好不容易走出石塔，队伍只剩下1/3的人。出石塔后是片针叶林，正值秋天，树叶有黄有红，景色愉悦非常振奋人心。我们准备穿过这片树林去汇合大部队（大部分人都相信在这样的巨灾下，会有机构或组织牵头准备全人类的避灾点），却发现怎么走也走不出森林。即使这片小林子肉眼可见的迷你，宛如一个街心公园一样大，可以透过树木看到那边的草甸，再看到那边的马路，但是走了很久却依然绕不出去。

我们坐下休整，意识到七星连珠后，虽然仿佛一切如常，但世界已经变了，而那个号称可以保证我们安全的石塔似乎也并没有起到什么作用。我与A仔细询问了这个石塔的背景，他说这是古玛雅人留下的遗址，在上古的七星连珠时，古玛雅人建立了这座石塔，认为可以连通古今，保人灵魂不灭。我问七星连珠后世界到底会发生什么灾难性的改变？目前似乎并没有体现出来。A说七星连珠产生的巨大引力会撕裂原子级别的互相作用，最有可能发生的就是基础物理性质的改变；而古玛雅人的石塔所谓“保人灵魂不灭”他更怀疑是让我们像西西弗斯一样永远困在了自己的精神世界中，所以这片森林有可能永远也走不出去。还有一个可能是七星连珠后，物理实体世界与精神意识融为一体，但是这都不好做推断下结论，因为毕竟没有人知道现在的世界可能是怎么样的，我们所掌握的物理规律也只是上一次七星连珠后的遗留，这次七星连珠后，世界的一切都会被洗盘，我们面对的是一片迷雾，除了前进别无他法。

和A聊完，我感觉似乎讲了很多，却又对我们现在的处境毫无帮助。如果只有石塔可以保留我们的意志不灭，是不是地球上的其余人都已经死亡或者变化成别的。修整后我们继续前进，领头的几个走得越来越快，小队逐渐排成了一字形前进，但即使这样也一直在树林里打转。更令人绝望的是，我们看到了草甸和小路上走着别的路人（石塔中走散的先行几个人），和我们一样也始终没有走出自己的这条路。也就是说现在的情况像多个回字嵌套，即使你可以从内层的圈横跨到外一层的圈，你还是在打转走不出去。领头的B（某乐手，没想到做梦梦到是这种角色）认为目前占领高地可以更有效地观察这一片的地势，突然他发现在肉眼可及的范围内，已有他的两个分身走到了草甸、和树林的另一侧。我们一行人都惊了，竟然出现了三个B，是因为他走的太快把自己走散了吗？但是没人想花太多精力思考为什么，毕竟七星连珠后的世界什么都有可能发生。B也没有太惊讶，他意识到自己有分身后完全可以利用这个优势去观测地形，于是他指挥着另外两个自己横跨到了另外两个圈的高地，并带我们走出了这片森林。

穿出森林后，场景立即就变化了，前面出现了一片用乳白石块嵌着七彩碎瓦片搭建的歪歪扭扭的城塔，笼罩着乌云下起了绵绵小雨。我们这行人只剩下了五个人，在狭窄的小路上向白城塔走去。不知道何时，背后突然出现了另一行人，很热情地和我们打招呼，说他们也是历经波折走到了这里。我们一看，对方嬉皮笑脸就很反常，而下着雨没有打伞身上却一点也没有湿，立即反应过来不是常人，撒丫子就回头往前奔。越奔近白城塔，雨越大，走到后面瓢泼大雨天色昏暗，而白城塔却离我们越来越远被浓雾笼罩，脚下只有一条狭窄小路，两侧均挖了很陡的路槽，也没有别的路可选。前方雾中突然几个穿着全黑斗篷的人在大雨中骑着自行车出来，看他们神似死神的穿着就知不是好惹的。但是只有一条路避无可避，我们几个人急中生智，贴边躲在了︿形路槽两侧，因为陡深所以骑自行车的死神在路上并看不到我们。

躲过一劫后我们加速向前，并遇到了自行车停车处，好几辆黑衣人的备用自行车停在那里。我们想说是不是可以蒙着黑衣偷骑他们的自行车伪装是自己人？结果发现这几辆自行车只能向反方向骑，那就很南辕北辙，只能放弃了这一想法继续向前走。这时雾散了雨停了，白城塔开门走出了一队人，他们皮肤、衣物、装饰全都苍白，近看原来是用白垩泥捏成的人，嘻嘻哈哈簇拥着他们的女王出城，女王倒是肤色正常，穿金戴银，头上顶着用白垩土做的皇冠，嵌着大红宝石，一脸高傲地倚在坐辇上。再走近后，我发现这些白泥随从样貌都很熟悉，竟然都是我的同学们！他们泥土做的四肢和五官都无法移动，脸上只有一张大嘴咧到嘴腮，白色的眼珠子左右乱瞟。我们又是无处可逃，也不知对方有无恶意。女王看见了我们五个，让她的白泥随从们停了下来，她下来接见我们，并赠送给我们五人每人一样白泥饰品。我的朋友们收到了白泥做的胸针、领带、戒指、项链，当他们接过这礼物，发现这白泥还未干透，一接手就湿嗒嗒地粘在了皮肤上，接着皮肤也逐渐变成了白色的湿嗒嗒的泥土，逐渐扩散到全身，把他们也变成了全身白色的土人。女王对此颇为满意，见状送我最后一样礼物：白泥做的手表。我自然是打死也不要，她便让随从强行把我摁住，自己将湿嗒嗒的白泥手表往我手腕上扣。谁知道这手表靠近我的皮肤后并沾不上去，女王气急败坏，尝试多次竟然都没有用，问我怎么做到的，我说可能是小时候做陶艺做多了对泥巴不敏感，不如放我走吧。女王不乐意，就非得和我僵持在那里，就这样对峙了许久许久，突然又下起了小雨，女王大惊失色，赶紧吩咐随从回城，但是已经来不及了，那些白土做的随从逐渐融化在了雨水里。

</br>

### 2020-04-10

我在BDO式巨型建筑物里上学，方方正正的全对称苏式设计，内外通体全是黑色花岗岩，楼里没有做自然采光，室内开的灯微乎其微，作用是只能照亮你在地板上的倒影。我接到了hr打来的电话，和我说他们公司裁员了，她自己也要收拾东西走了，没法帮到我什么。

我挂掉电话在校园里游荡，碰到了刚隔离完来上学的同学，同学一见面远远地就咳了起来，也没戴口罩，咳完用袖子抹了一把，上来见我就要抱我。我大叫讲点卫生，别跑来碰我。她便不，跑过来就又搂又抱还要给我翻衣领。我警告她够了，不要逼我翻脸。她还是不听，搂着我咳嗽。我气到用胳膊箍住她的脖子，让她适可而止。她一下被我箍得面容发紫，喘不过气，咳嗽也咳不出了。

保安闻风一下就跑过来了，叫来了景茶把我围作一圈。我继续箍着我同学的脖子，以她做人质，让周围人不要轻举妄动，全都放下武器退散到以我为中心半径五米的范围外。景茶保安都不理我，我一狠心把我同学的小拇指给折断了，这下大家都慌了，把枪都扔了，自动退散开。我听见周围看热闹的同学小声讲“没想到她还能真干出这种事”。我箍着人质，快速向校园大门挪动，在经过了一段又缓又长的象牙白大理石楞齿坡道，终于到了校门口。我把同学扔开，自己飞奔出了学校。

门口正好有一辆刚下客的出租车，我一开门直接挤进了副驾驶座。车很小，挤进去发现更小，头顶顶着天花板，腿只能曲着抱在怀里，屁股一边挨着车门，一边和司机屁股是挨着的，也没开空调，我可以感受到车门缝的冷空气往我屁股下钻。司机是一削瘦的北方爷叔，穿着肥厚的破棉服，戴着前进帽，脸上花白的胡茬赛过皱纹，一看就是没过几天好日子的劳动人民。司机问我去哪儿，我说跑路。“跑路是吧？诶好嘞”。

司机一路带我开上了北京环城高速，非常随意地开着。我在十层楼高的车道上，看着周围一片破败的筒子楼，灰沉的天色，一湾黄江水，倒有点像重庆嘉陵江的景色。牵牛花的绿藤从河床一直攀到了房屋的上沿，小小的紫色花朵倒是颇为可爱。但是再一瞧视野里的所有画面，几乎一棵树也没有，就江边几颗弱柳。我撇嘴说“北方怎么都没有树呢”。司机说“哪儿没有树了，这不都是树吗”。我呵呵，这也叫树吗？你真该看看南方的树，那茂密旺盛的，才叫树。他说他没出过北京，不知道那是长什么样的。

我很纳闷“我这不是在做梦么，按理逃出学校后，我这梦就该结束了啊，怎么现在还在做”。司机笑了“既然梦还在做，那就继续做呗”。说着说着他的小车就越往右侧歪，这立交桥上也没有防护栏，再出边一点就直接掉下桥了。我赶紧捏着两人中间的方向盘，往左边打了一点。司机不以为意，说就算不从右边掉下去，也容易从左边掉下去，他之前就掉下去过。

就这样他的车晃晃悠悠，宛如醉酒驾车一般，终于下了高速，开进了市区。我在车里翻动着他的东西，一切都陈旧得很，不是结了灰就是秃了漆。我找到了他夹在缝里的名片，也是一张皱皱巴巴泛黄的小卡，上面仿宋字体特别90年代。我试图把他的电话号码背下来，说没准梦醒了还能靠记住的号码再联系。但是这个号是080开头的固话，我背了几位就没背住。

开进市区，人很少，街道也很干净。开过一段1.5车道的小路，左右行车辆都在花式避让，这段路两侧都是银杏树，处在逐渐变得金黄的季节。这是法国街，有法使馆，还有叫avenue sonnet hotel的法资老饭店，路边若干个时尚博主在凹造型拍照。开出这段银杏小路，又开进了八车道的干道，像是到了城郊，树多了起来，高楼都没有了。路边有个北京红叶馆，破败的外墙面和旧于时代的建筑设计，大喇叭女声播着“首都红叶馆，有各种品种真假枫树，欢迎参观”。我说我可真想去看。司机说他在这儿这么久也没有去看过。然后我大声哭了起来，说自己永远不会去看的。司机很奇怪“你不是刚才还说很想去看吗”。我说我知道红叶是很好很好的，可我提不起劲去看你知道吗，我这辈子也不会去看的。

/后来我醒了

/我不知道会不会真的有个司机下午打盹时梦到载我一段

</br>

## 2018

### 2018-02-21 三个奇怪的梦

1.在从小熟悉的工人老小区闲逛，突然发现之前老年人压腿的街心花园变成了一个巨大的祭祀花园，按八卦方位放满了巨大的黑铜动物雕像，大概有四层楼那么高，个个狰狞可怕，而且都是猪鬃秃鹰山羊之类非常见动物。园内有游客中心和介绍板，原来按流程走一遍就是古人的cult施法现场。我逛了一半，感觉这地方一片死寂连虫鸣鸟叫也没有，更别提别的游客，吓得匆匆离开。出来了外面依然是鸟语花香人头熙攘，截然不同的世界。回到家里觉得很莫名，为什么从来没有经过听说这个地方呢？网上搜了一下全无痕迹。具体地址我也没记住，之后过去那片街区则再也看不到了。

2.一个人准备出来吃酸菜鱼，在街上晃了半天准备坐地铁去吃。该城市的地铁建的错综复杂又豪华，一个站有地下若干层楼，每层是不同的地铁线路，还可以从地下直连到附近公交车和轮渡。我下到地下四层去坐地铁，周围上班族来来往往（参考人广），突然有个大胡子中亚人在路中央放下了他的硕大背包，并开始叽里咕噜情绪激昂说话。我一想，不好这个人要当人肉炸弹。然后飞速往出口方向跑。周围路人还没反应过来，我一边跑一边叫BOMB!BOMB! 过了几秒钟所有人都反应过来了全都往地面方向跑。但是地铁站里的设计简直有毒，标了很多方向有很多通道但都不是去地面的逃生出口。地铁站里的人都惊慌了，甚至还有人跳上开来的地铁妄图逃生。工作人员的指引也是微乎其微。最后我废了九牛二虎之力终于蹿上了地面，那里有一些撤离用的小巴士，将我们撤离到市中心广场去。途中有只小猫咪试图搭车，我把它抱了上来，结果它挠了我几爪然后跳车了……因为该城的地下结构很脆弱，一旦在地铁深度引爆炸弹，可能会导致连锁反应，而地面又有大量高层建筑，一旦倒塌后果不堪设想。乘着巴士到了安全点，一车人都心情很低落，因为家人和孩子都不知道是否安全。我在安全撤离点看到了我妈却不知道我爸在哪里。因为上班时间他们也是分开撤退的。

3.在豆瓣上吐槽同学，结果被好事者截图发在了微博上，不知道为什么转发就过k了。然后就每天惴惴不安害怕被三次元熟人看到。私信这个好事者让他删除，他没有回我。然后我为了自保把豆瓣注销了

</br>

### 2018-01-14

感觉好几个月没做过大梦了，这次是架空朝代，封建体制和很多风俗被保留但同时科技教育也都很昌明。我在朝中当官，大致是一个手上有权有兵但又很闲的锦衣卫头头之类的官。

这天被我的好友王侍郎叫去家中做客。王侍郎家中也算官宦世家，从太祖朝就世代为官。然而王侍郎这一代家道不知为何中落，他自己本身科考庶吉士出身，前十年是官运亨通，中途被人以莫名理由弹劾，皇帝偏偏还信了，虽然也没被撤职查办，但给打发到南京来养老，随后原配妻子也和他离了婚，带着一儿一女不再与他有交集。

王侍郎还有两个姐姐：二姐嫁给了有名的富二代，本来也算是吃喝不愁了，只是富二代吃喝嫖赌毒样样都来，婚后不过五年就毒品过量而亡，分遗产的时候才发现他老爸那点钱早就被他挥霍在海洛因和俄罗斯转盘上了。而王侍郎的大姐一生未嫁，英年早逝，却是京城里的八卦传奇人物。小道常说这位王氏风姿绰约，年满十五就长得艳丽人间，各方相亲对象递帖子排队可从王府排到长安街上，京城里几个有名的阔少也常夸口立志娶王小姐为前半生的目标。她父母有这么个宝贝女儿自然是捧在手心里，给她最好的教育，送她去大不列颠留学。然后，据说王小姐在留学时邂逅了当时的太子（也就是当今的皇上）两人情投意合。京城圈子本以为郎才女貌，王小姐进入皇室指日可待，谁知王小姐怀孕流产紧接着被抛弃了，回国后大门紧锁，精神受到了严重打击，没过多久就暴毙而亡。她父母也是看名节看得重，打死也不让王小姐的棺椁迁入祖坟，说会破坏风水的，最后草草一埋也不知道成了哪里的野坟。自打这一事件起王家家道中落，事事不平，坊间刻薄者都说王氏父母封建思想洗脑的厉害，委屈了女儿，反倒害了风水。舆论也非常想谴责皇帝薄情寡义，但是敢这么叫嚣的媒体都被河蟹了。再过几十年，王家和皇室都对这件事缄口不提，事实更加扑朔迷离；更有阴谋论说王小姐只是想炒作自己名媛身份，没想到胡乱消费皇家声誉被暗地里谋杀了。

今天我去王府，看到宅院里杂草丛生，本应该维护得很好的园林假山流水都一片死寂景象，那么大的屋子却只留了几个老佣人来打点家事。王侍郎在客厅里见我，也是一脸萎顿，他见我来了叫人上了杯茶就开始讲：“我也不说废话了。我最近被医生查出肺癌晚期，估计时日无多了。但是王家还有一些事情不能没有终结，” 我想啊才四五十就得不治之症，真的是平时生活作息很重要哦。

“xx（我的名字），虽然我们相识多年，官场上互相照应，但我一直把你当外人，王家很多风言风语不平事你也有所耳闻，我一直没有告诉过你我大姐的事情。” 我内心：反正我也不关心啊。

这时一个中年妇女从内房走了出来，保养的很好姿容也可以推断年轻时一定是个美人，我想这一定就是二姐了。简单引荐后，二姐和王侍郎开始给我交待背景：“外面一直觉得我们大姐死得冤屈，我家父母冷血无情，几乎是抛尸荒野了。但事情不是这样的，大姐死后我们收到皇帝的帖子说想要他来负责大姐的选址下葬。那我们家自然是不允，本来就被薄情渣男害得惨，死后还要和皇家不明不白吗？我们回复了来传旨的徐公公，却紧接着又发了旨意，皇帝非常执着要由他亲葬，还带了封信帖，说是曾经写给大姐的信要一起埋在土里。我父母看皇帝这个阵势怕是非得不可，他们便打算先不回旨，然后紧急下葬，已经入土为安了总不好意思再重新挖出来吧。只是再去找大姐的棺椁时发现不翼而飞了！父母思量大约是皇帝偷偷摸摸派特务干的，当时也不敢撕破脸，日后却也没有机会撕破脸。以至于我们王家现在也不知道大姐的尸首在哪里，父母也都是含恨而走。我们俩姐弟也无能，现在眼看王家家道中落，三弟时日无多，但总想把这件事查个水落石出，所以这才拜托你。”

我自然是答应了，然后问他们有没有相关案卷可以看，他们说他们家一直有家族档案的，连同当时皇帝那份信都留着。二姐给我找出了皇帝那份信，火漆还未拆，他们说既然没有能力查证，还是不拆为好。于是这份信就到我手上拆了，我拆开一看密密麻麻写了千字，夹文夹白，匆匆看了一遍，姐弟俩问我写了什么，我说：“你是个好姑娘，只是我们俩没缘分。我喜欢上别人了。” 然后我们纷纷吐槽还真是典型渣男说法，我又问二姐要存档，她说在湖那边的藏书阁库房里。

我就从大堂走小木桥穿过湖，一边走一边想，不愧是曾经辉煌过的家族，居然地产里还有个湖。正走神着，突然一个杀手一脚把我踹下了桥，幸亏湖上停了很多小木船，还没站稳杀手就冲我扔飞镖，一边扔一边在码头上的小木桩用刀刻画什么。我躲过好几个飞镖，跳上岸把杀手擒获，当然杀手及时的自杀了，我再一看他用刀刻的，居然是每次扔飞镖的角度计算，我想这个人是不是强迫症难怪扔不准。上了岸想，为这破事居然还有人暗杀我，看样子真的是背后有猫腻。

出了王府，王侍郎叫司机开车送我回去，一路上他和我说，其实他叫我来除了让我查这件事，还有别的事情要麻烦我。我惊了，拿我当私家侦探吗又不给钱的咯。王侍郎接着说这件事是有报酬的，他说他和他前妻的离婚手续现在也没办清楚，而且他怀疑他的儿女在他前妻那里被带坏，他希望我去帮他找到可以重新获得抚养权的证据。我想，真特么一个主线任务一个支线任务。

操这个梦怎么这么长。。。总之最后我去王侍郎儿女在的高中里卧底，发现他女儿和她前妻都在吸毒，于是直接报警扔进派出所，估计戒完毒又会给放出来。

然后王小姐的故事，是皇帝其实对她念念不忘，听说她死了就想给她安葬到一个风水宝地。而负责传旨的徐公公贪恋这块佳穴，暗地里做手脚把这个风水眼改造成了可以给他自己招财进宝，然而对王氏弊大于利的墓穴。我们去找坟的时候一路挖沟，土层里面全是稀世珍宝。而无怪乎王家家道中落。

以及我的下属全是一群帅哥（。

</br>

## 2017

### 2017-11-13

我是长征大军的一员（我应该是领导），为了躲避果党追击，我军从湘赣一路往西逃。在逃亡的路上与大部队失去联系，我们的方向感也逐渐迷失。只觉得海拔一天比一天高，路途一天比一天陡峭。开始还有本地乡民踩出的土路，后来只有悬崖峭壁。

这天我们在翻过一座土山后就开始徒手攀山，说也奇怪，在山腰处发现一个豁口，走进去发现是一小片盆地，正对着的就是白雪覆盖的唐古拉山脉。很多同志经不住高原反应，脚步一停就开始哇哇作呕。我觉得还凑合，估计海拔在三千左右，再往上我也走不动了。

小队休整了一下，才开始观察自己所在的这片腹地。我发现有很多农作物，例如小麦，西红柿，黄瓜等等，但他们看起来都已经缺乏打理很多年了，杂草遍生。穿过耕作地后，才看见一排低矮的房屋，围绕着矩形的耕地。最醒目的无疑是一个砖制斜顶的小教堂，天主教的十字架在这种环境下显得尤为醒目古怪。

我们逐渐走近，才发现这里的村庄完全没有人，但大多是砖土房屋，也看不出被荒废了多久。越想越觉得诡异。我给小队下了指令，让他们四处侦查一下，而我叫了几个人一起去教堂侦查。走近教堂才发现这个教堂非常小，开了木门基本没多少空间，大概就是个牌坊矗在这儿。倒是隔壁居然有一个砖制的公共厕所。推门进隔间发现横卧着一具焦黑的骨骸。

此时外面队员的喊声也此起彼伏，在各家都发现了焦黑尸骸，估计就是死去的村民。他们一个个死相惨烈，脊椎外翻，看起来像是同一时间大规模死去的。有人分析可能是某种致命传染源，建议我们立即将尸体封土，并且对村庄进行消毒。这个建议受到大家一致认可。于是各个成员挖坟的挖坟，消毒的消毒。

我则负责厕所的这具尸体，将他好不容易拖到了室外，用锄头想刨一个坑，却发现土质太硬不好挖，而且没挖多少就已经撅到岩石层。此时焦骨却开始发生变化，骨头开始震动，发出爆裂的声音。我想不好难道要尸变，看着也没时间挖坟了，直接把尸骨扔到了旁边的石槽里，浇了点水和成湿泥，将石槽封了起来。

</br>

### 2017-10-18

我发现不穿内裤容易做春梦是真的。

第一个梦，学校组织秋游，然后我在外面打野炮。回来学生处主任拿着打印的监控录像，说要这个人自己出来承认，不然就到处贴大字报批判ta让ta身败名裂。然后又拿出一张个人信息表，说这个人的身份其实早就被掌握了，还是乖乖站出来的好。然后我一气之下就直接和学校打官司，告他们侵犯隐私权。

第二个梦。我的视角是一个十几岁小萝莉，父母离异，现在和同父异母的弟弟生活在一起。然后男主是我的青梅竹马，我一直暗恋他来着。但是他最后喜欢上我弟弟，我也就没再说什么。然而我弟某次火灾全身严重烧伤，不治身亡。蹊跷的是当天晚上我的继母就莫名受孕，最后生下来一个有外星基因的与我弟弟长相类似的男孩。男孩长到我弟死掉的那个年龄时，长相至少有八成相似了，男主又爱上了他。我去质问他你怎么能这样见异思迁呢？他说他只是想把这个有外星基因的男孩的皮剥下来，然后试着复活我弟弟。

</br>

### 2017-09-26

第一视角，女主（以下简称我）死爷爷死爸死妈（但并不是我死）

我的爷爷几年前死于风雪之夜的车祸中，后证实是人为谋杀。我的爸爸掌握巨头公司的违法犯罪证据，被灭口于家中。经过几年的调查，我追查到了这个不法公司，原来一切的主脑早已卸任退居二线。我得知他将以知名校友的身份参加其高中的圣诞交响音乐会，并发表结束致辞。

碰巧我的小学同学也是那所高中毕业的，我便假装在附近吃饭，制造了偶遇小学同学，几番搭讪后，我也如愿混到了交响音乐会的入场邀请函。在入场的时候，迎宾人员拦住了我，说我着装不符合要求（我穿着T恤热裤，但要求正装入席），为难之际还在想要不要去偷套清洁工衣服穿算了。所幸碰到好心的保安把他的长款风衣（见基努李维斯那种）脱下来给我穿。然后我就顺利混入场内。

中途借口上厕所离席，然后去舞台附近踩点，看看哪里下手比较合适。顺了别人的单反，假装自己是摄影师，躲在谱台后面，正好是个背对目标的绝佳位置。等了一会儿，演出结束，那个主脑上台发表结束致辞。面对舞美聚焦的灯光，他开始发表他的长篇大论客套之词，相信他还不知道自己即将面对什么。我等他站定了，佯装拿着单反拍照一点点靠近他，觉得时机成熟后，从口袋里掏出手枪，瞄准他的后脑勺，完美射击。因为装了消音器（不要问我什么时候装的），观众一开始还没有反应过来，等到他扑街在地滚下舞台，人群才一片惊慌四处逃散。我把指纹一擦枪一扔外套一脱连硝烟反应都没有，完美，准备开始跑路。

跑到一半的时候，想起之前做的背景调查，他家还有一个妻子一个儿子，只拍到了别墅小区的俯瞰图，不知道具体位置。我想，与其等以后被报仇，不如先下手为强，斩草除根。附近兜了兜，正好看到绿化设计和照片一模一样的小区，但是因为具体不知道是住在哪幢楼里，决定在附近隐姓埋名先观察一阵子。发现小区里有个美式餐吧正好在找女服务员，就去应聘了。应聘成功后，餐厅经理说要请我吃一顿汉堡，然后我就醒了（。

</br>

### 2017-05-25

搭乘公车去找c大同学玩，同学事先和我打好招呼，他们的宿舍在一个鸟不拉屎的地方。我想再怎么鸟不拉屎肯定也比不过我们（。

从市区搭乘那种90年代台湾的小公车，一路坐到了终点站，我们下车，下车才发现落脚之地都没有，因为周围一大片荒地都是深灰色的沼泽地，散发着腐烂的恶臭，沼泽区域中间夹杂着一些发秃的黄土地，我们就踩着间隙一路向北走，走到了宿舍区。他们的宿舍楼是一栋栋灰色水泥筒子楼，底楼长年潮湿阴暗，水泥缝长着青苔都变绿了。宿舍里更是常年不见太阳，还是一种黄梅天东西都捂馊的味道。

这一片楼处在灰色的沼泽之中。向北方望去却能看到仿佛近在咫尺的山脊。灰白色的外层在顶峰被风化，露出内里鲜红色的岩石层。整个山脉像一条死去动物的尸体横卧在沼泽中。

这破地方我一分钟也不想久留，就和同学说要先搭乘公车回去了。等待公车的人很多，公车也来的很快，一下子小车就被挤满了，准备往回开。公车却没有沿原路驶回，往着更加荒芜的腹地开去，在一个段爬坡的山路停住，车上乘客都以为车抛锚了什么的，纷纷下车，发现这段山路上居然装了类似铁轨的东西，正当纳闷，山顶居然有车急驰而下，也没有刹车，直接从没有护栏的山路飞了出去。又冲下来两辆卡丁车，上面绑着两个白人，我们纷纷贴着山壁避让，却还是有很多人被撞飞。这时不知道哪里来的喇叭传出广播：既然好不容易来了，为什么不学习一点知识呢？我们将给你们安排三次考核，只有通过的人才有资格离开！

当我们还在回味这是什么意思的时候，山顶就放出了很多丧尸，飞奔着跑向我们。我们连滚带爬回到了公车上，人已经零零散散死了一半。公车又自动开了，开去了一个学院。那里有老师会先教我们一些基础技能去应对接下来的考核。学院外围养着一群丧尸，他们看起来估计不是韩国丧尸就是日本丧尸，被圈成一周，有人脑残去撩拨他们，他们发出grrrr的声音冲过来却又被无形的东西限制住。

这个老师教的是植物，带着我们在植物组织培养间介绍这介绍那，当然此时我并不在听课，我溜到了建筑外围，用手扒着护栏，踩着空调机围着这幢建筑指望能逃脱。但是发现学院外围裹着一片森林，逃脱几率不大。下课了，我只好又爬回楼里。

第一次考核紧接着就开始了，我们被车拉往这片森林的另一端，说希望我们能从这里逃生。这片森林看起来啥也没有，十分人畜无害。但接着就有人认出了这里树上结的果子，在lab里看到过，非常危险。这时树上像毛栗子一样的果实都裂了开来，里面飞出了长着尖刺的种子，见人就扎，很多人不留神就死在了树下。我和几个人勉强逃出森林。

森林外是个废弃的城市，好在我们还发现了一辆停在路边的白色桑塔纳，开着小车缓缓地驶在城市道路上，生怕又有什么关卡。然后我们就发现了大批丧尸，我们立马提高车速，生怕这些丧尸扑过来。但这群丧尸仿佛十分慵懒，也就一开始追着我们小跑几下，然后就不追了。成群结队站在路边，苍白的脸上涂着黑色油彩，仿佛还有种夹道欢迎的样子。

越往城市里开好像就越少安全地，于是我们决定再开回森林那片，毕竟那里的学院楼应该是安全的。我们赶紧逃进一桩楼的其中一个房间。但是森林那些果子仿佛长了眼，不依不饶，飞行力度能破窗穿墙，又扎死了很多人（包括这个楼里的研究人员）。有个大佬叫到：是紫外！他们吸收光波！实验室里的紫外对他们有害！快把这个房间里的紫外打开！

我还一脸懵逼（因为没有好好听课），他让我们赶紧把这个房间的门窗都紧闭，窗帘拉上。他出去找了一个黑人研究员让他打开紫外（为什么这里有黑人呢？因为美国电影里总归有个黑人）这步花了很久，因为这套房间是多人宿舍，大大小小套了很多门窗。等到一切都处置完了，也听不见那些果子飞行时的嚣叫声了，我们都松了口气。

结果门外突然又传来了尖叫声，肉体撞击声和不明物体发出的喘声，根据我多年经验判断出这是丧尸，估计刚刚那个黑人小哥领便当了。没有想到这幢楼里还藏着我们绝不愿意碰到的东西。听声音丧尸朝我们这过来了，他像查寝大妈一样居然透过门上的玻璃想看里面的动静。我们几个人立马趴在地上装死，那个丧尸在门口看了又看，地上的光影变了又变，最后它还是没有进来。

我和大佬准备商量后事，进了一个小间，结果发现这个卧室床上居然还坐着一个小姑娘，一脸萎顿看着我们。我说，按照套路这个女的待会儿一定会变丧尸。大佬说，那怎么办呢。我说，先下手为强吧。然后我们打开窗子，把她扔了出去。

夜幕降临，看样子我们这四个是这批人里仅存的活口，大家都很困倦。大佬给我们鼓气说，这个房间暂时是安全的，大家好好休息一晚，我们明天离开这个鬼地方。我们都很累，想到明天或许能回家，又有些激动，但是丧尸那么多，如何突出重围还是个问题。最后大家都睡过去了。

</br>

### 2017-04-24

新学期开学，学校里出现了很多新面孔，都打扮的非常时髦，穿着花花绿绿的衣服。我问同学这些是不是转校生，但是同学都说他们一直在这里念书。

重新分配寝室，原来寝室的同学说她们要新加一个成员，让我自己去找别的寝室。别的寝室都满了，最后我只好和一群边缘型人物住。

寝室聊天我就说，感觉有很多新面孔和新变化，可是别人都没发现。寝室里大家却都发现了。

我抓了一个新面孔，他说他只是植入的程序。这个世界是一个虚假的世界。他告诉我程序的漏洞，可以通向真实的世界。

我找到了漏洞。外面是一片城市废墟。

</br>

### 2017-04-12

有个变态绑架了六十只猫，从高楼上一起扔下去。

我看着一只只猫尖叫着从天空掉下来，在地上摔到内脏都流出来，一片血地。

警察在房顶上抓他的时候，看到现场惨象都忍不住作呕

</br>

## 2016

### 2016-12-11

已经连着一周做梦做到出冷汗惊醒了。

我和一群女生在灾难后被人救起，安排住在地下的一个设施中，命运由老板规划。或是当女佣或是当娼妓或是当有钱人的情妇。我们的灵魂球（不要问我这是什么）都被锁住灵魂室里面。一日我得以偷偷潜入灵魂室，将自己的灵魂球偷带出去。地下设施庞大，像迷宫一样蜿蜒复杂，摸索了半天找到了正门，万幸门的磁锁坏了，顺利逃出。
出门上到地面发现是热闹非凡的商业街，出口出被掩饰成废品收购站，竟然无人起疑心。刚逃出没多久，老板的大儿子就带着追兵过来抓我。我冲进商场里只想坐地铁回家，和追兵在商场里兜兜转转逃了好几圈，终于进入了地铁口。
地铁口正门写着：上了地铁就可以回家。
地铁内部早已被清空，他们安排了无数怪兽在甬道里埋伏我。狼人僵尸剑齿虎，一个个扑上来咬我。我逃过了一关还有一关，自认无法成功逃脱，拍地认输，这时老板的大儿子就将我带了出去。
出去时我反客为主，将老板的儿子用手臂箍住脖子，让杂鱼不要轻举妄动。并威胁要把他们地下的勾当公之于众。
老板的儿子也不是吃素的，居然险些挣脱了我的控制。然后我们两个人扭打了起来。然而我并打不过，又被抓了起来

</br>

### 2016-11-12

最近好久没做梦了。一做就做了两个。

第一个：
家里终于养了只猫。因为我爸妈说家里出现了老鼠，虽然我一直没看到。
直到有一天我终于看到了，从墙角裂缝里钻出一只纯白的，迷你如柳絮的小东西。更像是什么白色的原始足虫。接着又钻出一只，稍大，像是刚从子宫里剥离的白鼠。一只又一只，越来越大，直到体态接近正常灰鼠。
我觉得事态不对，踩上了一只凳子。此时脚下已四处是蹿动的老鼠了。他们突然开始打架撕咬。多是两只合力去围攻另一只，将它的肚子咬开，内脏流出了一地，接着顺着伤口将整个毛皮撕扯下来。然后两只老鼠很有默契的将这坨毛皮内脏的混合物拖到了墙皮里面，再将地上渗着的血沫拭干净。
它们就这样一只一只的互相戮杀，互相将对方的肠子拉扯出来，遍地都是碎了的内脏、血沫、毛发。
我都看懵逼了，看了半天想起来这场面太危险，大叫到：“猫！快来救我！”
（ps，画面血腥是平生做梦之最）

第二个：
啊起床去做实验了。有空再写吧

</br>

### 2016-10-12 抑郁面馆

中午饭都没来的及吃就躺床上睡着了，做了个梦。

有一家面馆，专门为抑郁症患者服务。我去吃面，面馆很小很油腻，座位都挤在一起，明明有几个空位，老板娘却说那些地方都是有人的，让我等等。
过了一会儿，老板娘给我发了牌子，指手让我坐在一个中年上班族的旁边空位上，“我们这儿门面小，大家免不了要拼桌。不过来这吃面的人都很友善，自来熟。”
我坐下了，面还没上来，先端上来一碟花生和海带丝。我只好先一粒一粒的吃起花生来。
旁边一个人吃完了自己碗里的面，他说他在这里的日子结束了，他要自杀了。
我身边的上班族站起来劝他：“别这样，高兴点。”
“我的生活里已经没什么值得高兴的事了。”
“要逼自己保持高兴！这样生活才能继续。”
“这样有什么意义吗？无非是欺骗自己，欺骗生活。”
说完他就冲出了面馆，跳楼自杀了。
上班族又坐下吃面，面馆里其余人更是没有抬头。
而此时我的面还没有端上来，梦就已经醒了。

醒来我飞速点了个外卖。

</br>

### 2016-05-04

下午没课就睡着了，直到刚才室友回来开灯闪瞎我我才醒

和爸爸妈妈坐飞机去台湾玩，只飞了半个小时，飞机上睡一觉就醒了。醒了才发现飞机是个黄黄破破的民用小飞机，落地的时候夕阳了，发现机场也是那种民用小机场，黄黄破破的。

下了飞机什么手续也没有，出了停机场就是城市，这时天一下子暗了，路灯都亮了起来。街道都平平矮矮的房子，亮起了黄色的灯（像宫崎骏那种。很多年轻的姑娘走在街上，几乎可以说只有年轻的姑娘，她们大多打扮时髦性感，站在街旁抽烟招揽生意。我在黑漆漆的街区里迷失了方向，旁边不像是住宅也不是商业楼，看过去的时候大部分都只是被道路划分成的一块块黑色的区域

我一个人漫无目的的转着，直到被路人送到了派出所，他们好像不知道大陆是哪儿，也不关心，就把我搁在一个地方说会有人来处理的。结果那是精神病院。我发现里面一半都是小动物，他们都不疯，看起来很正常，大家都把这里当做收容所，日式房间里总是洒满了夕阳时的光辉。

我不想总是呆在这里呀，我就溜了出去。白天的道路十分清晰，我走到了市中心，走到了商业区。商业区的摩天大厦一个个都像是蓝色的铅笔（玻璃幕墙建筑，上海中心那种），更奇异的是他们都戳在水中。蓝天白云在上，蓝天白云在下，就像是用水银铺满了大地做成了一面镜子。可是人群、很少的人，依然像有土地那样走在上面，沿着斑马线过着红绿灯。我试着伸出一只脚点地，发现原来地上是一层积水，看样子是下过了雨。

台湾是有山有海的。我仿佛是站在海里往山眺望。那里是一个个筒子楼，砖红色的却是用泥土堆砌的。一个个红楼挤满了山坡，上面开着一个个方块窗子。这情景不免让我想起小学做的陶艺课，紫红色的陶泥成板隔成一个筒子楼，一座座楼挤在小小的地方，越堆越高。看着不禁有些反胃，便不再看去。

又回去了精神病院，因为我除了那里也别无可去。电视说最近飞行事故总是出，迷迷糊糊的。我隐约想起来飞来台湾的时候，显示屏上插播了飞800年后台湾的广告，我是点了吗？还是没点？

医生正在做团体心理辅导，小姑娘抱着我说我是她弟弟，而她弟弟却在屋里跑来跑去。轮到我了，我说我只是一个回不了家的人，不知道为什么和你们一群人一群小动物呆在一起。大家都怔怔的看着我，医生问我哪里有小动物？我随手一指，那是个小鸡，那是个小狗。医生给我做了微电刺激，再让我看，说那分明是一个老奶奶和一个小姑娘。我的视野中真的他们慢慢从小鸡和小狗变成了老奶奶和小姑娘。我说我正常了。可是看着他们我却觉得很诡异。

他说我这是xx旅行的后遗症，可能有幻想症和精神分裂症。那我就很疑惑，我看到的城市，有多少是真有多少是假呢？

后来我回家了，可是我不知道爸妈在哪儿。一切就像是刚离开的那样。或许他们去上班了还没回来吧，我这样想着。然后坐在马桶上准备打电话给同学，同学接了电话，我却觉得电话那头是那样陌生。

</br>

### 2016-01-16

amy是个长得比较高大的女性，她有一种超能力，不知道是放出波还是射线。之前谈的几个男票全被射线搞得癌症死。亲戚朋友都嫌弃她，不敢与她过多来往。这天晚上家里正聚餐呢，amy伪装成大龄剩女的样子，老老实实在桌角吃饭，亲戚朋友也伪装对她并无芥蒂的样子，但暗地里手脚都搁着远远的不想自己与她过多接触。有亲戚背地里说叨，怎么就想不开要过来吃这顿饭寻癌得了呢。

这是个侏儒，他长得和各大好莱坞魔幻片中的侏儒一样猥琐惹人厌。他的名字大家不记得，反正直叫小矮人就可以了。小矮人晚上来这家餐馆寻amy，因为boss有事要把他们这群人给凑起来。刚进餐馆门，amy的亲朋好友就坐不住了，一眼便知这是谁的怪模怪样的朋友，amy的朋友一定也是有害的。amy承认这确实是她的朋友，一时间辱骂叫嚷声不断，叫这二人赶紧滚蛋。amy受着旁人的不待见已经习惯了，拉着小矮人的手准备离开，小矮人的脾气可都不厚实，直接吹了一把火搞得众人衣服裙子胡子都焦了，看着他们大呼小叫的这才满意地跟着amy离去。

背后又是一阵辱骂，amy控制不住自己的情绪，对面街的玻璃房子被震得玻璃碴四溅。amy蹲下把小矮人护住，小矮人觉得这个高大女性能给他从未有过的温暖。(不要问我为什么一开始做梦上帝视角还有支线人物的感情戏)boss其实也不是boss，只是他们这群主流边缘的怪异人士组成的一个小团体的发起人而已。
amy和小矮人赶去大本营的时候，其他身怀异术的团员也在赶过去。

大本营的入口和众多大本营的入口一样，一定是不起眼的，愚人耳目的。这天深夜，我在这片筒子楼只想找个理发店把头给剪了。三家理发店排成一字，门面都很小，估计只有一两个位子一两个师傅给剪。看起来深夜但是生意依旧很好，我在三家门面前面来来回回晃悠了几十步，依然不见空闲下来的师傅。嘿里面师傅居然以为我是来大本营集会的，莫名其妙就把我放了进去。

理发店后面是一石砌的老洋房，boss在不着灯火的一楼给一帮人讲情势，世界要毁灭啦，拯救世界的关键就在这个老洋房的地下室。那是一片被封印诅咒的异次元，如今封印马上就要破啦，恶魔小鬼猛兽都要被放出来危害人间了，地狱的赤焰会把人世间一切东西烧为灰烬，幸亏我得到了消息，提前封锁了这块地方，如今还有机会挽救啊，只要我们这群人团结起来，就能把诅咒给破了。

大家纷纷说好。地下室的门开了，里面的空间大到无法想象，有岩浆黑石，也有绿藤罗曼。不远前地上就有一块灰黑色由8*8方石拼成的巨大浮雕，boss说这既是诅咒也是封印，那石头里面有怨毒的恶灵和不得安生的死魄，浮雕就是前人用来压制的咒语，我们只要把浮雕修改一二，便能让诅咒石瓦解。

哇听上去很容易，但这是手头上错了一两分就要悲剧的事情。boss说此等重要关节，有闪失就堕入万劫不复炼狱，我也不勉强大家，大家也没有这样的能力，我就自己上吧。大家纷纷鼓掌。然后大boss把我拉了过去，说此事须二人配合。我心中一万个wtf。那能怎么办呢，他让我改哪儿我改哪儿呗。

一会儿，搞完了，石块碎成了渣渣。boss长舒一口气，大功告成。石块碎了留下了如岩浆蚀过后炽热的红色边缘，石块碎了我们没地儿站只好往后退一步咯，没想到那红色边缘向我们逼近，脚下石地也纷纷碎裂落下。我一望，下面简直是被火烧过的万葬坑啊。我们越退越快，脚下的地也裂的越来越快。后来大boss眼见实在退无可退，反倒要牵连他人，长叹一口气，拉住了我往下跳。地不再碎了，后面人惊呼。我和大boss一齐掉入万丈深渊，本以为会掉很久，没想到biaji一声落地了。诶？原来这坑这么浅！真是白捡一条小命。

我正想爬上去，大boss拉住我，别动你抬头看。我一抬头，发现坑与地面中间好像隔了一层介质，模糊着并看不清楚，而上面事物好像快进了一般，刹那间便是沧海桑田。

大boss说，似乎这上下是两个时间线不同的空间，现在贸然上去恐怕不妥，不如静观其变。于是我们在下面等着，其实也没等多久，撑死几小时，但是上面的变化却是巨大的。他们来了走，走了来，恪杀了异兽小禽，搬来石头木料，修桥建池，看的我颇为不解。过了好一会儿，上面终于看不见变化了，我和大boss爬了上去，发现上面的空间被他们改造成了一个小村庄，俨然一片世外桃源。

屋子里住的都是从前跟着大boss的人，有的甚至组建了家庭，繁衍了后代。我和大boss在下面不过待了几小时，上面变化却已不可消化。走进一家孤灯点着，是理发店的老板，一小老头，大boss问了他那日之后的事。小老头说，那日我和大boss掉下深渊，上面人都看的分明，救是救不回来了，而既然石碑已碎，诅咒也破除了，此地也没什么好逗留的了，于是关上地下室的门，封上符咒，这个团也就此散了。没想到后来这块地始终是非多，被政府发现，想要进行调查实验，舆论又开始攻击超能力人士，眼看要将他们除之后快。他们在外面也是左挡右避，终日煎熬，再加上不欲这片地方被政府着手，妄生事端，他们几个索性心一横，花了几年功夫将此地改造得宜居，将门用恶性符咒封死，从此隐居在其中。

大boss一直想有一番作为，没料到事情会如此发展，也只能又悲又叹，余生也只能像其余人一样，活在这片空间中。

</br>

## 2015

### 2015-02-28

学校要放假了。一放学，发现有只哥斯拉出来了，四处踩，把城市踩了个稀巴烂。我们躲在房屋中，摸索出一套规律。比如要把窗帘都拉起来，要不然怪兽特别习惯把爪子放进去乱摸。但如果拉上了窗帘，它就会懒得拉窗帘了再进去摸了。分昼夜模式，哥斯拉只在白天出来，晚上是休养生息，准备物资的好时机。
一晃眼，咦，学校原来还没有放假。但是我十分相信那个先兆，就和死神来了一样。所以我找班主任啊，老师让我提前溜吧，老师说，还有几个小时才放学，你得有请假条啊。我就打电话找爹妈，爹妈电话就是打不通。眼见着哥斯拉就要来了，我不能困在学校里被踩死啊。所以当机立断，拉着群小伙伴就直接冲出学校了。

走之前，学校里来了个神棍，说什么这个世界，即将通过一段四维扭曲，会裂变成三个平行世界（黑板上画着彩虹桥的图示。虽然只有我有灾难来临的vision，但是小伙伴都很相信我，和我撒丫子狂奔。奔到哪里去呢？我坚信，这个世界是有限的，就像是13th floor一样，等你跑到这个空间的边界，就可以到另一个平行世界中去。可是往哪儿跑比较近呢？
跟着直觉走吧，往西跑。。跑啊跑，跑到了一个很像日本宗庙的地方，还樱花阵阵飘啊。小伙伴说，你说跑过界限就能安全的了，可是这边已是尽头，根本没有路了啊！
我说，一定会有的。只不过我们不知道而已。

有几只小猫和兔子在树下玩耍，我灵机一动。对！这就是命运给我们的hint。所以我唤醒一只小猫，跟着小猫狂奔。

最后。。好像只有我一个人奔的比较快，奔到了平行世界去吧。但是平行世界更悲惨，哥斯拉已经是定好了日期，明天就要来了。我靠我赶紧叫上老爹老妈，收拾细软，拉上窗帘，给他们科普知识：躲在哪里比较不容易被哥斯拉踩到（这都是我做了无数被怪兽踩的梦得出的经验啊。

带好水和干粮，我们先躲在了地下车库。但是这里人太多了，几乎整个小区都躲在这儿了。我想万一怪兽一脚把地踩踏了，踩进地下车库怎么办？所以我们还是选择躲在地面上

还没躲好呢，怪兽就来了。一脚踩进我们躲的那个位置。我靠只好一边狂奔一边躲啊，躲哪儿怪兽踩哪儿也是跪了。。这怪兽是不是和我有仇啊。

第一波怪兽攻击结束。下一波又是几天后。这几天的时间里，我和我的小伙伴找到了楼梯后的密道。居然是堆满金币和财宝的金库。同学说，这里最有价值的就是圣杯，用圣杯接上长生不老泉的水，可以获得永生，就是这个圣杯被埋葬在金堆里找不到了而已。我手一捞，捞出来个小杯子，不会是这个吧。。咦就是这个！

泉水从自来水管道里流出，味道特别难喝，就像是氯气加足的自来水。喝了也没啥感觉，就又出去了。

物资极其匮乏，所以在地下车库里，大家分享食物。每个家庭出一道菜，围坐而食。

哥斯拉又来了。这次我躲在河边花坛下，我想这次怪兽总不会发现了吧

但是，怪兽又发现了。一脚把花坛踩踏了。我只好怒目而视怪兽的眼睛，怪兽居然用洋鬼子腔对我说：“窝补事股亿的，泥袋者把。”